name: CI/CD Model Classification Freshness

on:
  push:
    branches:
      - "main"

env:
  TAGS: v1.0.9
  DOCKER_REPOSITORY: fruitarians-model
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      -
        name: Configure Docker credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:v1.0.9
      -
        name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_REPOSITORY }}:v1.0.9"
          credentials: ${{ secrets.GCP_SERVICE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: asia-southeast2
          service: fruitarians-model-cloud-ci-cd

